### PR TITLE
json format does not allow two dots in numbers

### PR DESCRIPTION
**Pull request by Coeur**
A number in json format can have one dot at most: http://www.json.org/

### CODE REVIEW

**Comment by Coeur** [comment]
@sbenedicadb no comment on this?

**Comment by hunterpeterson** [comment]
@Coeur,
Sorry for the confusion, I believe @sbenedicadb fixed by moving to a string format in the json. This is a package file that is not in use currently, so was not causing issues anywhere. Thanks for the feedback and cleanup!

**Hunter Peterson**
*Lead Mobile Engineer*
[Adobe Marketing Cloud](http://www.adobe.com/solutions/digital-marketing.html)

**Comment by Coeur** [comment]
@hunterpeterson thank you for the feedback. But as the pull request wasn't merged, it wasn't fixed either.

**Comment by hunterpeterson** [comment]
@Coeur,
The fix was implemented in the following commit: https://github.com/Adobe-Marketing-Cloud/mobile-services/commit/290a52fec9c9fcc9a2dff0780f8b6a3a8ed4ad53. 

**Hunter Peterson**
*Lead Mobile Engineer*
[Adobe Marketing Cloud](http://www.adobe.com/solutions/digital-marketing.html)

**Pull request closed without merging**
