### PR TITLE
iOS 4.5.2 release

### PR DESCRIPTION
**Pull request by shalehaha**

### CODE REVIEW

**Comment by jeremyfpope** [comment]
Does this support arm64?

**Comment by shalehaha** [comment]
@jeremyfpope, yes. And here is the list of architectures that we're supporting : armv7 armv7s arm64 i386 x86_64.

**Comment by jeremyfpope** [comment]
Thanks for the quick reply.  Any idea why Xcode would give "undefined symbols" when I try to compile using 4.5.2?

Undefined symbols for architecture arm64:
  "_adb_GetMarketingCloudID", referenced from:
      _ADBMobile_adb_GetMarketingCloudID_m27 in Bulk_Assembly-CSharp-firstpass_0.o

This is for a project built using Unity.

**Comment by shalehaha** [comment]
@jeremyfpope , I just ran a Unity app with 4.5.2 SDK, and I didn't get any compile error. Could you give me more info, like which SDK version were you using before?If fall back to 4.4.1 version, do you still get the same error? And it would be much more helpful if you could provide me the source code.

**Comment by jeremyfpope** [comment]
@shalehaha , sorry I haven't yet had a chance to test this out.  When I have the time I'll test it and let you know the results.  Unfortunately, I can't share the source code.

**Comment by jeremyfpope** [comment]
@shalehaha , it looks like the project was linking to version 4.4.0 when those errors were generated.  The project is compiling without issue using the latest Unity plugin (v4.4.2).  Apologies for the mixup!

**Pull request merged**
